name: mi primer hola mundo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  sayHello:
    runs-on: ubuntu-latest
    name: Say Hello
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  sayGoodbye:
    runs-on: ubuntu-latest
    name: Say Goodbye
    needs: sayHello
    steps:
      - name: Run say goodbye
        run: echo Goodbye, world! 